name: frontend-backend-pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
          echo "MYSQL_DBNAME=${{ secrets.MYSQL_DBNAME }}" >> .env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env
      - name: check the files
        run: ls
      - name: Start containers with Docker Compose
        run: docker compose up -d --build

      # - name: Run tests
        # run: docker compose exec app npm test

      - name: Stop containers
        run: docker compose down
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build services
        run: docker compose build

      - name: Push frontend Image
        run: docker push ghcr.io/sriram-tecneu/project-frontend:latest
      
      - name: push backend Image
        run: docker push ghcr.io/sriram-tecneu/project-backend:latest
      
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}-backend:latest
            docker pull ghcr.io/${{ github.repository }}-frontend:latest

            docker stop backend || true
            docker rm backend || true

            docker stop frontend || true
            docker rm frontend || true

            docker run -d -p 5000:5000 --name backend ghcr.io/${{ github.repository }}-backend:latest
            docker run -d -p 3001:80 --name frontend ghcr.io/${{ github.repository }}-frontend:latest
